### ISSUE TITLE
Bug fixes and improvements checklist

### ISSUE THREAD

**Issue by huynhsontung** [huynhsontung/Screenbox#34]
- [x] Disable appropriate player buttons when there is no current item
- [x] Keyboard accelerators can trigger when buttons are not on screen
  - [x] Player more options menu
  - [x] Main page back button (can be triggered when player is on top)
- [x] Fix notification button shows up as empty
- [x] Validate keyboard navigation
- [ ] ~~Better UI indicator for volume boost (use warning foreground color)~~
- [x] Background transition when the player is visible. Right now the main page just collapses when the transition happens.
